// pylon-web/src/pages/Login.tsx
import type { ChangeEvent, FormEvent, FocusEvent } from 'react'
import { useState } from 'react'
import { Code, ConnectError } from '@connectrpc/connect'
import { Link, useLocation, useNavigate } from 'react-router-dom'

import { AuthService } from '../api/auth'
import { useAuth } from '../hooks/useAuth'
import { useDocumentTitle } from '../hooks/useDocumentTitle'

type LoginFormValues = {
  email: string
  password: string
}

type FieldName = keyof LoginFormValues
type FieldErrors = Partial<Record<FieldName, string>>
type TouchedFields = Partial<Record<FieldName, boolean>>

type LoginLocationState = {
  registrationSuccess?: string
}

const initialValues: LoginFormValues = {
  email: '',
  password: '',
}

const fieldNames: FieldName[] = ['email', 'password']

export function LoginPage() {
  useDocumentTitle('Login / Pylon Web')

  const navigate = useNavigate()
  const location = useLocation()
  const { storeToken } = useAuth()
  const locationState = location.state as LoginLocationState | null
  const registrationSuccess = locationState?.registrationSuccess

  const [values, setValues] = useState<LoginFormValues>(initialValues)
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({})
  const [touched, setTouched] = useState<TouchedFields>({})
  const [globalError, setGlobalError] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)

  function handleChange(event: ChangeEvent<HTMLInputElement>) {
    const field = event.target.name as FieldName
    const nextValues = {
      ...values,
      [field]: event.target.value,
    }

    setValues(nextValues)
    setGlobalError(null)

    if (touched[field]) {
      setFieldErrors((current) =>
        updateFieldError(current, field, validateField(field, nextValues)),
      )
    }
  }

  function handleBlur(event: FocusEvent<HTMLInputElement>) {
    const field = event.target.name as FieldName

    setTouched((current) => ({
      ...current,
      [field]: true,
    }))

    setFieldErrors((current) => updateFieldError(current, field, validateField(field, values)))
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()

    const nextErrors = validateForm(values)
    setTouched(
      fieldNames.reduce<TouchedFields>((result, field) => ({ ...result, [field]: true }), {}),
    )
    setFieldErrors(nextErrors)
    setGlobalError(null)

    if (Object.keys(nextErrors).length > 0) {
      return
    }

    setIsSubmitting(true)

    try {
      const response = await AuthService.login({
        email: values.email.trim(),
        password: values.password,
      })

      if (response.token.trim() === '') {
        setGlobalError('Login response did not include an access token.')
        return
      }

      storeToken(response.token)
      navigate('/', { replace: true })
    } catch (error) {
      setGlobalError(mapLoginError(error))
    } finally {
      setIsSubmitting(false)
    }
  }

  function renderField(
    field: FieldName,
    label: string,
    type: 'email' | 'password',
    autoComplete: string,
  ) {
    const error = fieldErrors[field]
    const inputId = `login-${field}`
    const errorId = `${inputId}-error`

    return (
      <div>
        <label
          className="font-mono text-xs uppercase tracking-[0.22em] text-[var(--color-muted)]"
          htmlFor={inputId}
        >
          {label}
        </label>

        <input
          aria-describedby={error ? errorId : undefined}
          aria-invalid={Boolean(error)}
          autoComplete={autoComplete}
          className="mt-3 w-full border-2 border-[var(--color-ink)] bg-transparent px-4 py-4 text-base font-semibold outline-none transition-colors placeholder:text-[var(--color-muted)] focus:bg-[var(--color-grid)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-60"
          disabled={isSubmitting}
          id={inputId}
          name={field}
          placeholder={label}
          type={type}
          value={values[field]}
          onBlur={handleBlur}
          onChange={handleChange}
        />

        {error ? (
          <p
            className="mt-2 font-mono text-xs uppercase tracking-[0.16em] text-[var(--color-accent)]"
            id={errorId}
          >
            {error}
          </p>
        ) : null}
      </div>
    )
  }

  return (
    <main className="min-h-screen bg-[var(--color-paper)] text-[var(--color-ink)]">
      <section className="mx-auto grid min-h-screen w-full max-w-7xl grid-cols-12 gap-x-4 px-5 py-6 sm:px-8 lg:px-10">
        <header className="col-span-12 border-b border-[var(--color-line)] pb-4">
          <p className="font-mono text-xs uppercase tracking-[0.34em] text-[var(--color-muted)]">
            Pylon Web / authentication
          </p>
        </header>

        <section className="col-span-12 grid grid-cols-12 gap-x-4 pt-12 lg:pt-20">
          <div className="col-span-12 lg:col-span-6">
            <p className="mb-5 inline-flex border border-[var(--color-ink)] px-3 py-1 font-mono text-xs uppercase tracking-[0.26em]">
              Access terminal
            </p>

            <h1 className="max-w-4xl text-[clamp(4rem,14vw,10rem)] font-black uppercase leading-[0.84] tracking-[-0.08em]">
              Login
            </h1>

            <p className="mt-8 max-w-2xl border-t border-[var(--color-line)] pt-5 text-xl font-semibold leading-tight tracking-[-0.03em]">
              Authenticate through the generated Connect auth client and enter the protected app.
            </p>
          </div>

          <div className="col-span-12 mt-10 border-y-2 border-[var(--color-ink)] py-6 lg:col-span-6 lg:mt-0">
            {registrationSuccess ? (
              <div
                className="mb-6 border-2 border-[var(--color-accent)] px-4 py-3 font-mono text-xs uppercase tracking-[0.16em] text-[var(--color-accent)]"
                role="status"
              >
                {registrationSuccess}
              </div>
            ) : null}

            {globalError ? (
              <div
                className="mb-6 border-2 border-[var(--color-accent)] px-4 py-3 font-mono text-xs uppercase tracking-[0.16em] text-[var(--color-accent)]"
                role="alert"
              >
                {globalError}
              </div>
            ) : null}

            <form className="space-y-5" noValidate onSubmit={handleSubmit}>
              {renderField('email', 'Email', 'email', 'email')}
              {renderField('password', 'Password', 'password', 'current-password')}

              <button
                className="inline-flex w-full items-center justify-between border-2 border-[var(--color-ink)] bg-[var(--color-ink)] px-5 py-4 font-mono text-xs uppercase tracking-[0.22em] text-[var(--color-paper)] transition-transform duration-200 hover:-translate-y-1 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0"
                disabled={isSubmitting}
                type="submit"
              >
                {isSubmitting ? (
                  <>
                    Signing in
                    <span
                      aria-hidden="true"
                      className="ml-8 size-4 animate-spin border-2 border-[var(--color-paper)] border-t-transparent"
                    />
                  </>
                ) : (
                  <>
                    Sign in
                    <span className="ml-8">↗</span>
                  </>
                )}
              </button>

              <Link
                className="inline-flex w-full items-center justify-between border-2 border-[var(--color-ink)] px-5 py-4 font-mono text-xs uppercase tracking-[0.22em] transition-transform duration-200 hover:-translate-y-1 hover:bg-[var(--color-accent)] hover:text-[var(--color-paper)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--color-accent)]"
                to="/register"
              >
                Don&apos;t have an account? Register
                <span>→</span>
              </Link>
            </form>
          </div>
        </section>
      </section>
    </main>
  )
}

function validateForm(values: LoginFormValues): FieldErrors {
  return fieldNames.reduce<FieldErrors>((errors, field) => {
    const error = validateField(field, values)
    if (error) {
      errors[field] = error
    }

    return errors
  }, {})
}

function validateField(field: FieldName, values: LoginFormValues) {
  switch (field) {
    case 'email':
      if (values.email.trim() === '') {
        return 'Email is required'
      }
      return undefined

    case 'password':
      if (values.password === '') {
        return 'Password is required'
      }
      return undefined
  }
}

function updateFieldError(errors: FieldErrors, field: FieldName, error: string | undefined) {
  const nextErrors = { ...errors }

  if (error) {
    nextErrors[field] = error
  } else {
    delete nextErrors[field]
  }

  return nextErrors
}

function mapLoginError(error: unknown) {
  const connectError = ConnectError.from(error)

  if (connectError.code === Code.Unauthenticated) {
    return 'Invalid email or password.'
  }

  if (connectError.code === Code.InvalidArgument) {
    return (
      cleanBackendMessage(connectError.rawMessage || connectError.message) ||
      'Login input is invalid.'
    )
  }

  if (connectError.code === Code.Unavailable) {
    return 'Login service is unavailable. Please try again.'
  }

  return 'Login failed. Please try again.'
}

function cleanBackendMessage(message: string) {
  return message.replace(/^invalid input:\s*/i, '').trim()
}

// pylon-web/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";
  import { AlertCircle, ArrowRight, Lock, Mail } from "lucide-svelte";

  import {
    hasLoginFormErrors,
    validateLoginForm,
    type LoginFormErrors,
  } from "$lib/auth/login-validation";
  import { auth } from "$lib/stores/auth.svelte";

  let formData = $state({
    email: "",
    password: "",
  });

  let errors = $state<LoginFormErrors>({});
  let apiError = $state<string | null>(null);
  let isSubmitting = $state(false);

  onMount(() => {
    if (auth.isAuthenticated) {
      void goto("/");
    }
  });

  async function handleSubmit(event: SubmitEvent): Promise<void> {
    event.preventDefault();

    apiError = null;
    errors = validateLoginForm(formData);

    if (hasLoginFormErrors(errors)) {
      return;
    }

    isSubmitting = true;

    try {
      await auth.login({
        email: formData.email.trim(),
        password: formData.password,
      });

      await goto("/");
    } catch (error) {
      apiError =
        error instanceof Error
          ? error.message
          : "Unable to sign in to your Pylon account.";
    } finally {
      isSubmitting = false;
    }
  }

  function clearFieldError(field: keyof typeof formData): void {
    if (errors[field] === undefined) {
      return;
    }

    errors = {
      ...errors,
      [field]: undefined,
    };
  }
</script>

<svelte:head>
  <title>Sign in · Pylon</title>
  <meta
    name="description"
    content="Sign in to the Pylon distributed real-time chat control surface."
  />
</svelte:head>

<main class="min-h-screen bg-zinc-950 px-5 py-8 text-zinc-100 sm:px-8">
  <section
    class="mx-auto flex min-h-[calc(100vh-4rem)] max-w-5xl items-center justify-center"
  >
    <div
      class="w-full max-w-md border border-zinc-800 bg-zinc-950 p-5 shadow-[12px_12px_0_0_#bef264] sm:p-8"
    >
      <div class="mb-8 border-b border-zinc-800 pb-6">
        <p class="text-xs font-black uppercase tracking-[0.28em] text-lime-300">
          Login
        </p>
        <h1 class="mt-3 text-4xl font-black tracking-[-0.04em] text-white">
          Back to the grid
        </h1>
        <p class="mt-3 text-sm leading-6 text-zinc-400">
          Sign in with your Pylon credentials and continue to the realtime chat
          control surface.
        </p>
      </div>

      {#if apiError}
        <div
          class="mb-5 flex gap-3 border border-red-500/70 bg-red-950/40 p-4 text-sm text-red-100"
          role="alert"
        >
          <AlertCircle class="mt-0.5 size-4 shrink-0" aria-hidden="true" />
          <p>{apiError}</p>
        </div>
      {/if}

      <form class="grid gap-5" novalidate onsubmit={handleSubmit}>
        <label class="grid gap-2" for="email">
          <span class="text-sm font-bold text-zinc-200">Email</span>
          <span class="relative">
            <Mail
              class="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-zinc-500"
              aria-hidden="true"
            />
            <input
              id="email"
              class="w-full border border-zinc-700 bg-zinc-900 px-11 py-3 text-base text-white outline-none transition focus:border-lime-300"
              class:border-red-400={errors.email}
              name="email"
              type="email"
              autocomplete="email"
              placeholder="alice@example.com"
              bind:value={formData.email}
              aria-invalid={errors.email ? "true" : "false"}
              aria-describedby={errors.email ? "email-error" : undefined}
              oninput={() => clearFieldError("email")}
            />
          </span>
          {#if errors.email}
            <span id="email-error" class="text-sm font-semibold text-red-300">
              {errors.email}
            </span>
          {/if}
        </label>

        <label class="grid gap-2" for="password">
          <span class="text-sm font-bold text-zinc-200">Password</span>
          <span class="relative">
            <Lock
              class="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-zinc-500"
              aria-hidden="true"
            />
            <input
              id="password"
              class="w-full border border-zinc-700 bg-zinc-900 px-11 py-3 text-base text-white outline-none transition focus:border-lime-300"
              class:border-red-400={errors.password}
              name="password"
              type="password"
              autocomplete="current-password"
              placeholder="Your password"
              bind:value={formData.password}
              aria-invalid={errors.password ? "true" : "false"}
              aria-describedby={errors.password ? "password-error" : undefined}
              oninput={() => clearFieldError("password")}
            />
          </span>
          {#if errors.password}
            <span
              id="password-error"
              class="text-sm font-semibold text-red-300"
            >
              {errors.password}
            </span>
          {/if}
        </label>

        <button
          class="mt-2 inline-flex items-center justify-center gap-3 bg-lime-300 px-5 py-3 text-sm font-black uppercase tracking-[0.18em] text-zinc-950 transition hover:-translate-y-0.5 hover:shadow-[6px_6px_0_0_#3f3f46] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0 disabled:hover:shadow-none"
          type="submit"
          disabled={isSubmitting}
        >
          {#if isSubmitting}
            <span
              class="size-4 animate-spin rounded-full border-2 border-zinc-950 border-t-transparent"
              aria-hidden="true"
            ></span>
            Signing in
          {:else}
            Sign in
            <ArrowRight class="size-4" aria-hidden="true" />
          {/if}
        </button>
      </form>

      <p class="mt-7 text-center text-sm text-zinc-400">
        Need an account?
        <a
          class="font-bold text-lime-300 underline decoration-zinc-700 underline-offset-4 hover:text-lime-200"
          href="/register"
        >
          Create one
        </a>
      </p>
    </div>
  </section>
</main>
